---
#
# Copyright (C) 2024 James Cherti | https://www.jamescherti.com/contact/
# URL: https://github.com/jamescherti/be-quiet.el
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.
#

name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - 26.3
          - 27.1
          - 28.1
          - 29.1
          - 29.4
        python-version:
          - 3.11
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: actions/cache@v2
        id: cache-cask-packages
        with:
          path: .cask
          key: cache-cask-packages-000
      - uses: actions/cache@v2
        id: cache-cask-executable
        with:
          path: ~/.cask
          key: cache-cask-executable-000
      - uses: cask/setup-cask@master
        if: steps.cache-cask-executable.outputs.cache-hit != 'true'
        with:
          version: snapshot
      - run: echo "$HOME/.cask/bin" >> $GITHUB_PATH

      - name: Install
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          python -m pip install ~/melpazoid

      - name: Run melpazoid
        env:
          RECIPE: (be-quiet :repo "jamescherti/be-quiet.el" :branch "${{ github.ref_name }}" :fetcher github :files ("be-quiet.el"))
          EXIST_OK: false
          CASK_PATH: $HOME/.cask/bin
        run: 'echo -e "Ref: $GITHUB_REF\n$(emacs --version)" && make -C ~/melpazoid'

      - name: Run tests
        run: make test
        env:
          CASK_PATH: $HOME/.cask/bin
